FROM php:7.4-apache
RUN docker-php-ext-install mysqli
COPY index.php /var/www/html/index.php
COPY message.php /var/www/html/message.php
COPY cr7.php /var/www/html/cr7.php
COPY km10.php /var/www/html/km10.php
COPY lm10.php /var/www/html/lm10.php
COPY r9.php /var/www/html/r9.php
COPY r10.php /var/www/html/r10.php
COPY kb9.php /var/www/html/kb9.php
COPY styles.css /var/www/html/styles.css
